### ISSUE TITLE
Name of Debian Package

### ISSUE THREAD

**Issue by free-x** [kdschmidt1/Sail_Instrument#1]
Hi,

wäre es möglich Package umzubenennen? z.B avnav-segeldisplay-plugin oder noch besser irgendwas internationaler?

Gruß
free-x

**Comment by kdschmidt1** [comment]
Hi,
Ich plane ohnehin das repository umzubenennen, z.b. SaiI-Instrument.
Gruß kd

**Comment by kdschmidt1** [comment]
Solved with [20220505](https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20220505)
