### ISSUE TITLE
How to Convert Polar to polare.xml

### ISSUE THREAD

**Issue by free-x** [kdschmidt1/Sail_Instrument#2]
Hi,

wie kann man Polardaten automatisch polare.xml aus z.B. von https://www.seapilot.com/wp-content/uploads/2018/05/All_polar_files.zip

Gruß
free-x

**Comment by kdschmidt1** [comment]
Hi,
Ich werde im nächsten nächsten Release einen Vorschlag dazu im Readme darlegen. (Angedacht ist, das ganze über Excel zu machen), da die Messblätter zu den Booten in unterschiedlichsten Formaten existieren. 
Dauert aber noch ein wenig, da Andreas gerade das Interface zu AvNav komplett überarbeitet. Da sollte es dann auch einen (Daily)-Build geben, mit dem man das ganze testen kann.
Gruß kd
