### ISSUE TITLE
More Calculations based on Signalk Plugin

### ISSUE THREAD

**Issue by oxbown** [kdschmidt1/Sail_Instrument#20]
Hi! First of all, I appreciate your work to bring the community the awesome plugin for Avnav.
There is a plugging for signalk that makes calculations based on data (the same way that you do). Some of the calculations are not in the Avnav plugin. 
https://github.com/SignalK/signalk-derived-data/tree/master/calcs

**Comment by kdschmidt1** [comment]
Hello oxbow,
i´m well aware of SignalK and its plugins and use it on my own boat as a gateway to the NMEA2000 Network and to read Victron devices. But AvNav has to work also as standalone Application and is therefore calculating all necessary signals for the sailinstrumen display itself.
One can also observe some errors in the SignalK calculation (i.e. see [readme](https://github.com/kdschmidt1/avnav-more-nmea-plugin) of more-nmea plugin) which are currently also lead to a modification in upcoming AvNav version <[issue#320](https://github.com/wellenvogel/avnav/commit/443428c7a561b86b2b95c8f5cc46671228f33a7c)>.
After a complete recoding of the calculaion part of the software together with @quantenschaum we are quite confident to have the correct calculations in sailinstrument. Feel free to use the plugin together with SignalK, but be aware of correct configuration to avoid signal interferences.
Regards kd

**Comment by quantenschaum** [comment]
As @kdschmidt1 already mentioned, AvNav should work w/o SignalK, too. Furthermore I suspect some of the calculations in the SignalK plugin to be wrong. The plugin should be thoroughly tested and the results of both plugins could be compared. There is also a problem with the definition of some data paths in SK, see https://github.com/wellenvogel/avnav/issues/320. Without an unambiguous definition of what the values in these paths actually mean, it's impossible do write down the correct equations.
