### ISSUE TITLE
Docs im Wiki

### ISSUE THREAD

**Issue by quantenschaum** [kdschmidt1/Sail_Instrument#21]
Du hast die Dokumentation erweitert und ins Wiki verschoben. :+1: 

Das Wiki hat leider den Nachteil, dass man keine pull requests machen kann. Und die Bilder, die Wiki referenziert werden, liegen ja auch noch im eigentlichen Projekt. 

Wie wäre es, statt des Wikis einen `doc` Ordner mit den entsprechenden Markdown Files und Images im Projekt selbst zu haben? Dann funktionieren auch pull requests.

Ich wollte noch die theoretischen Grundlagen der Berechnungen beschreiben, was auch für SignalK interessant sein kann (#20).

**Comment by kdschmidt1** [comment]
Hallo Adam,
die Wiki-pages sind jetzt im repository unter docs verfügbar.

**Comment by quantenschaum** [comment]
Danke.

Es gibt übrigens in github [discussions](https://docs.github.com/de/discussions/quickstart). Könnte sinnvoll sein zum besprechen von Details.
