### ISSUE TITLE
Sail_instrument plugin run finshed

### ISSUE THREAD

**Issue by AaskovKnudsen** [kdschmidt1/Sail_Instrument#25]
Hello
I have been using sailinstrument version 20240503 for a while and is very happy with this avnav plugin.
It works fine for a long time, but suddenly it terminates with the message system-Sail_instrument plugin run finished.
Please see attached image.
I have seen that 2 times. Restarting avnav cures the problem.
I attach the avnav logfile. Latest  issue was at 2024 07 02
Avnav version 20230705.
Best regards
Jan
![screendump 2024-07-02 173606](https://github.com/kdschmidt1/Sail_Instrument/assets/150262992/b7482cf8-a44d-4bad-aa02-edb85614f117)
[avnav.log](https://github.com/user-attachments/files/16071236/avnav.log)

**Comment by kdschmidt1** [comment]
Hello,
I had a look in the log file, but could not find any issue.
I would like to ask you to install the  following prerelease [20240704](https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20240704) that has some aditional logging support and to send me the resulting log-file if the failure reappears. thank you for your support.
regards kd

**Comment by AaskovKnudsen** [comment]
Hello Schmidt, and thank you for the advice.
I am at vacation just now, but will do it when I get back .
Thanks
Jan

tors. 4. jul. 2024 13.40 skrev kdschmidt1 ***@***.***>:

**Comment by quantenschaum** [comment]
I observed this, too, but it's unclear to me how this can happen. There is a [catch all](https://github.com/kdschmidt1/Sail_Instrument/blob/fa073abffe3412c2cc9e9beb2fe49a1350199361/Sail_Instrument/plugin.py#L530) in the main loop, so it should keep going.

**Comment by AaskovKnudsen** [comment]
For your information, I have not seen this issue since I reported it in july. I have been using avnav and sailinstrument heavily the whole summer.

**Comment by quantenschaum** [comment]
Well, then should close this and reopen if necessary.
