### ISSUE TITLE
Extending Polare

### ISSUE THREAD

**Issue by Fietsenwiel** [kdschmidt1/Sail_Instrument#4]
Is it possible to extend the polare.xml with more wind speeds and angles?

From for example:
<windspeedvector>[4,6,8,10,12,14,16,20,25,30]</windspeedvector>
<windanglevector>[32,36,40,45,52,60,70,80,90,100,110,120,135,150,160,170,180]</windanglevector>

To:
<windspeedvector>[4,6,8,10,12,14,16,20,25,30,**60**]</windspeedvector>
<windanglevector>[32,36,40,45,52,60,70,80,90,100,110,120,**130,140**,150,160,170,180]</windanglevector>

I understand that if you do the boatspeed table, upwind and downwind has to be extended.

Thanks!

**Comment by kdschmidt1** [comment]
Common x-axis for boatspeed entries and upwind/downwind entries is the windspeedvector, so number of entries should be the same as windspeedvector for upwind/downwind and for every line in boatspeed.
regards klaus

**Comment by kdschmidt1** [comment]
Completed
