### ISSUE TITLE
Hi CPU load w/o NMEA data

### ISSUE THREAD

**Issue by Albert444** [kdschmidt1/Sail_Instrument#6]
Hi,
I want to hint at an potential issue that I encountered: after installing a completely new image from avnav on a Rasperry 4 and directly afterwards updating all plugins with the updater-plugin as well as installing the more-Sail_Instruments-plugin at home w/o any NMEA data available, the CPU load of one of the 4 cores of the Raspberry jumped to 100% and stayed there for 12++ hours. It went down again after disabling the plugin.
Maybe there could be a small function that pauses the plugin or puts it in an error state when there are no NMEA data available and prevent a permanent 100% CPU load?
Just a hint - maybe there is reason to this... thanks and best greetings

**Comment by kdschmidt1** [comment]
Hi Albert444,
I checked the issue with my desktop installation (with raspberry3), but could not reproduce the behavior.
could you please provide the avnav log and check the behavior with deactivated Sail-instrument plugin to be sure, that it is caused by the plugin?
regards klaus

**Comment by kdschmidt1** [comment]
Hi Albert,
this should have been solved with the new release https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20230728 that is already available by avnav-updater.
regards kd
