### ISSUE TITLE
Hohe Prozessorauslastung?

### ISSUE THREAD

**Issue by Schweensen** [kdschmidt1/Sail_Instrument#8]
Hallo kd,

ich habe in AVNAV das Problem das die eingehenden NMEA-Daten (per USB-NMEA-Adapter) nach dem Start des Raspberrys anfangs noch synchron angezeigt werden, je länger der Raspi aber läuft desto verzögert/zeitversetzt werden die Daten in AVNAV angezeigt. Nach einigen Stunden Laufzeit hat man schon 1-2Std. Zeitverzögerung. Wenn man im Hafen festgemacht hat, dann läuft das Boot auf der Karte in AVNAV noch munter weiter bis es dann irgendwann auch im Hafen ankommt. Es sind alle NMEA-Daten betroffen. 
Meine verbauten NMEA-Instrumente zeigen aber immer die aktuellen NMEA-Daten live an. Es liegt also nicht an der NMEA-Schnittstelle.

Sobald ich das builtin-sailinstrument in AVNAV deaktiviere laufen die NMEA-Daten in AVNAV wieder live und synchron. Es liegt irgendwie an dem Plugin.

Hast du eine Idee wie das zusammenhängen könnte?

VG,
Sven

**Comment by kdschmidt1** [comment]
Hi Sven,
currently there is no explanaition for this behavior, but please check with the new release https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20230728 that is already available by avnav-updater and reply with the result.
regards kd

**Comment by kdschmidt1** [comment]
Closed

**Comment by kdschmidt1** [comment]
Closed

**Comment by kdschmidt1** [comment]
C

**Comment by kdschmidt1** [comment]
C
