### ISSUE TITLE
ausrichtung HDG vs COG

### ISSUE THREAD

**Issue by quantenschaum** [kdschmidt1/Sail_Instrument#9]
Danke, geniales Teil!

Ich hab das mal ausprobiert und es scheint so, dass der rot/grüne Ring seinen Nullpunkt (Orientierung) am COG ausrichtet. Ich hätte erwartet, dass der Ring am HDG (heading, Vorrausrichtung) ausgerichtet ist. Der orange Marker sollte am COG ausgerichtet sein, die Zahl in dem Kasten sollte true HDG anzeigen. Oder fehlen mir irgendwelchen in AvNav? HDG und COG sind eigentliche beide vorhanden, AvNav zeigt die beiden Linien auch entsprechend an.

![image](https://github.com/kdschmidt1/Sail_Instrument/assets/3985599/47a0c77a-9494-474a-b801-ebc78e97e5a3)

**Comment by quantenschaum** [comment]
vgl. das wind widget von [KIP](https://github.com/mxtommy/Kip)

![image](https://github.com/kdschmidt1/Sail_Instrument/assets/3985599/895eea9a-f7d0-4a6f-a9a2-ea111f2f758b)

**Comment by quantenschaum** [comment]
Hier noch ein Beispiel, wo alles falsch zu sein scheint. Boot driftet seitwärts nach W
- Wind 090 
- HDG 000
- COG 270

Das wird dargestellt, im Vergleich dazu KIP (ist IMHO korrekt)

![image](https://github.com/kdschmidt1/Sail_Instrument/assets/3985599/8d3836f6-4c32-4cc5-87d6-bb369579c8d4)

- Es ist um 90° verdreht, da Ausrichtung an COG und nicht HDG
- Aber der true wind hat zusätzliche eine "seltsame" Richtung

Ich denke, da stimmt was nicht.

Das Ganze wurde simuliert mit diesen NMEA-Daten, welche an signalk gesendet wurden. Alles auf openplotter.

```
$GPRMC,194051.55,A,5440.614,N,01310.793,E,005.0,270.0,040224,4.7,E*5b
$GPGGA,194051.55,5440.61,N,01310.79,E,8,12,1.0,3.0,M,0.0,M,,*53
$GPZDA,194051.55,04,02,2024,01,00*6d
$GPGLL,5440.6145,N,01310.7934,E,194051.55,A*05
$HCHDG,352.9,2.4,E,4.7,E*4a
$VWVHW,0.0,T,355.3,M,0.0,N,,*31
$SDDBT,,,8.0,M,,*2e
$WIMWV,90.0,T,10.0,N,A*2d
$WIMWV,90.0,R,10.0,N,A*2b
$HCROT,0.0,A*2d
$RIRSA,0.0,A,,*34
$ERRPM,E,1,0.0,,A*6f
$CCVDR,270.0,T,,,5.0,N*5a
```

**Comment by kdschmidt1** [comment]
Hallo Adam,
vielen Dank für die Hinweise. Die Unterstützung für Heading habe ich erst im September 2023 hinzugefügt. Leider scheint danach etwas mit der Erzeugung eines neuen Release schief gelaufen zu sein und ich habe übersehen, dass kein neues Release erzeugt wurde. Ich werde mir auch die Zuordnung zu den Anzeigeelementen noch einmal ansehen und den Hinweis bzgl. TWD überprüfen und noch diese Woche ein neues Release veröffentlichen.
Sorry,
Gruss kd

**Comment by quantenschaum** [comment]
Ich habe auch mal https://github.com/SignalK/signalk-derived-data/ angesehen und festgestellt, dass viele Berechnung darin (set/drift, TWA/TWS, ...) falsch sind. Das scheint ein großes Durcheinander (in verschiedenen Projekten) zu geben bzgl. true/magnetic und bei den Vektorgleichungen zur Addition von Geschwindigkeiten. Da ist fast immer irgendwo ein Fehler drin. Ziemlich gefährlich, wenn mas einfach so benutzt.

**Comment by quantenschaum** [comment]
Ich hab mir einen [einfachen Simulator](https://github.com/quantenschaum/mapping/blob/master/ship_sim.py) geschrieben, der NMEA-Daten an SignalK damit auch AvNav sendet. Da ich die korrekten Werte kenne, kann ich damit überprüfe, ob das Richtige in AvNav/SK ankommt bzw. berechnet wird. Vielleicht kannst du das ja gebrauchen.

**Comment by quantenschaum** [comment]
Toll wäre noch der Pfeil in der Mitte, der die Wasserströmung (set/drift) anzeigt.

**Comment by quantenschaum** [comment]
Wenn man das Widget nicht auf der Karte verwendet, dann sollte es sich immer mit heading nach oben ausrichten.

**Comment by quantenschaum** [comment]
Auf dem aktuellen master scheint das zu funktionieren, auf openplotter mit plugin version 20230728 nicht.

- die Ausrichtung an der heading line ist richtig.
- die Berechnung/Darstellung von AWA und TWA ist falsch. Die Pfeile werden relativ zum COG positioniert, müssen an der HDG ausgerichtet werden. Das fällt auf, wenn man eine Abweichung zwischen COG und HGD hat, also Abdrift und/oder Strom.

**Comment by quantenschaum** [comment]
Ich habe mal in den Code geguckt und verstehe nicht, warum der true wind 2x berechnet wird.

1. im JavaScript-Code im Browser
2. im Python-Code auf dem Server

Der Code in 1. scheint keinen Einfluss auf die Darstellung zu haben, enthält aber den Fehler, dass `course` und `speed` COG und SOG entsprechen. Hier müssten HDG+leeway und STW verwendet werden. Der Python-Code scheint den selben Fehler zu enthalten.

**Comment by quantenschaum** [comment]
lesenswert 
- [Apparent Wind, True Wind and Ground Wind, and data required to calculate them](https://raymarine.custhelp.com/app/answers/detail/a_id/3794/~/apparent-wind%2C-true-wind-and-ground-wind%2C-and-data-required-to-calculate-them)
- [Essential Guide to Sailing with Instruments](https://busse-yachtshop.de/pdf/bg-triton-2013-bys.pdf)

**Comment by quantenschaum** [comment]
Ich habe das mal überarbeitet, vielleicht kannst du das übernehmen.

https://github.com/quantenschaum/Sail_Instrument/commit/071f034c4940da06b7c49ee605237f1ffb35a024

- Berechnung von TW aus AW und HDT/STW
- cleanup des Berechnungscodes
- keine Berechnung von TWA/TWS wenn diese schon vorhanden sind
- Überarbeitung der min/max-Berechnung für TWD
- Überarbeitung der Filterung, das ist einfach [exponential smoothing](https://en.wikipedia.org/wiki/Exponential_smoothing)

**Comment by kdschmidt1** [comment]
Hallo Adam,
danke für den Code und die Links. (Das war sicher kein Spass, meine SorceCode-Pflege und -Kommentierung ist wohl eher nicht vorbildlich). Ich werde es mir ansehen. (Aber warum hast du keinen Pull-request gesendet?)
Ein genereller Kommentar:
Wir sind hier im Open-Source Bereich für Hobby-Bootfahrer, mit einem kostenfreien Produkt. Das bedeutet, das Programm sollte auch mit einfacher (billiger) Bootsausrüstung funktionieren. Das war mein Ansatz. Idealerweise GPS und fertig. Aber selbst mit einem el. Kompass bekomme ich zunächst nur mgK-Daten. Was mache ich dann? mgK zur Berechnung nutzen?
Ich denke nein (War zumindestens in meiner Prüfung nicht zulässig). Daher überlege ich gerade, die magnetic-varation berechnung aus meinem anderen plugin zusätzlich zu implementieren, um zumindest rwK berechnen zu können, ich bin mir aber nicht sicher, ob das in ein plugin oder in avnav selbst gehört. Und dann bleibt immer noch die Deviation. Wohl nur die wenigsten von uns haben Deviationstabellen für ihr Schiff.
Das sind die grundlegenden Überlegungen, die ich mir für die Umstellung auf HDT stelle (Zunächst mal ein halbwegs zuverlässiges HDT erzeugen). Klar, für mich als Ostsee Segler war Tideneinfluss bisher kein Thema. Bitte verstehe mich nicht falsch, ich bin für jeden Input dankbar und werde selbstverständlich auch deinen Input bearbeiten, aber das ganze sollte auch für einfache Ausrüstung funktionieren und vor allem verständlich sein, Auf einer HR69 mit Vollausstattung wird wohl niemand avnav nutzen.
Bevor ich jetzt hier die ganze Kommentar-Funktion sprenge: Ich arbeite weiter an Verbesserungen und insbesondere Fehlerbehebung. Für weitergehende Diskussionen kannst du mich gerne auch unter meiner privaten mail kdschmidt@bluewin.ch kontaktieren um hier den Rahmen nicht zu sprengen.
Gruss kd

**Comment by quantenschaum** [comment]
Ja, den Code zu lesen, ist nicht so einfach. Aber egal, sehr schön, dass du das angefangen hast. Alles gut, wir können das ja zusammen "perfektionieren". Das hier aufzuschreiben stört ja niemanden, aber so können es andere auch lesen und ggf. mitmachen. Scheint aber nur eine Handvolle Leute zu sein, die sich damit beschäftigen.

Ich schreibe gerade alle nötigen Gleichungen zur Berechnung dieser Größen auf, als Grundlage. Man kann natürlich Werte ersetzen, wie COG anstelle HDT, als Näherung, wenn man nichts anderes hat, aber dann ist das Ergebnis eben entsprechend falsch.

Deviation spielt idR keine Rolle bei selbst-kalibrierenden elektronischen Kompassen, Missweisung schon. Letzere bekommt man aus dem WMM, wie du es schon machst. Viele GPS-Units spucken die im NMEA schon mit aus bzw. ein elektronischer Kompass macht das intern und gibt direkt HDT aus.

Interessant in diesem Zusammenhang: https://play.google.com/store/apps/details?id=com.meowsbox.netgps Damit kann man Kompass und GPS aus einem Smartphone benutzen, das man irgendwo festklebt.

**Comment by quantenschaum** [comment]
Nach meinen Änderungen sind die Laylines beide rot? Woran liegt das?

**Comment by quantenschaum** [comment]
Auf der Ostsee gibt's keine Tiden, aber dennoch Strömungen, die zum Teil erheblich sind. Auch binnen auf Flüssen strömt es. Das ist ja hier nerdiger Kram auch zum Spaß an der Theorie, wenn mans richtig machen will, muss man die Strömung mit einbeziehen.

Ich verstehe den Ansatz, dass man auch mit GPS allein etwas anzeigen möchte. Als Fallback kann man ersetzen

- COG --> HDT
- SOG --> STW

Man sollte eine entsprechende Warnung ausgeben/anzeigen, da die angezeigten Werte verfälscht sind.

**Comment by quantenschaum** [comment]
Hier die Formeln zur Berechnung von Kurs-Daten inkl. Code, der die fehlenden Größen berechnet.

https://github.com/quantenschaum/mapping/blob/master/coursedata.py

**Comment by quantenschaum** [comment]
Ich hab noch einen Strompfeil reingebastelt.

![image](https://github.com/kdschmidt1/Sail_Instrument/assets/3985599/93446207-8e36-4a36-a685-3ee5e693e3b0)

**Comment by quantenschaum** [comment]
Das Widget hab ich auch angepasst.

![image](https://github.com/kdschmidt1/Sail_Instrument/assets/3985599/9aaae1c3-fe95-4a29-82a1-50f2c0029866)

**Comment by kdschmidt1** [comment]
Sorry Adam,
Kann wegen einer Erkrankung zur Zeit nicht am PC arbeiten.
Werde den pull request baldmöglichst bearbeiten.
Gruss kd

**Comment by quantenschaum** [comment]
Alles Gute! Ich noch etwas weiter aufgeräumt und es flexible gestaltet.
